using Test

include("utils.jl")
@testset "aqua" include("aqua.jl")
@testset "interface - tests hcubature auxquadgk" include("interface_tests.jl")
@testset "brillouin" include("brillouin.jl")
@testset "fourier" include("fourier.jl")
@testset "executors" include("executors.jl")
@testset "DOS - test implicitintegration" include("dos.jl")
@testset "tolalg" include("tolalg.jl")
@testset "AutoBZCoreSymmetryReduceBZExt - tests ibz" include("AutoBZCoreSymmetryReduceBZExt.jl")
@testset "AutoBZCoreUnitfulExt" include("AutoBZCoreUnitfulExt.jl")
@testset "AutoBZCoreAtomsBaseExt" include("AutoBZCoreAtomsBaseExt.jl")
@testset "AutoBZCoreWannierIOExt" include("AutoBZCoreWannierIOExt.jl")
@testset "AutoBZCoreFunctionWrappersExt" include("AutoBZCoreFunctionWrappersExt.jl")